---
- name: install dependencies
  when: inventory_hostname in groups['VM1']
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
    with_items:
      - curl
      - openssh-server
      - ca-certificates

- name: install gitlab
  when: inventory_hostname in groups['VM1']
  apt:
    name: gitlab
    update_cache: yes
    state: latest
