---
- name: create a temporary build directory
  tempfile:
    state: directory
    suffix: build
  register: build_path

- name: send Dockerfile
  copy:
    src: '{{ role_path }}/files/{{ item.name }}'
    dest: '{{ build_path.path }}/'
  with_items:
    - "{{ images }}"

- name: build file
  become: yes
  shell: 'docker build --quiet -t {{ item.name }} {{ build_path.path }}/{{ item.name }}'
  register: image_id
  with_items:
    - "{{ images }}"

- name: tag images
  become: yes
  shell: "docker tag {{ item[0].stdout }} {{ hostvars['etna_vm1']['ansible_eth0']['ipv4']['address'] }}:5000/registry/{{ item[1].name }}"
  with_nested:
    - "{{ image_id.results }}"
    - "{{ images }}"

- name: push registry
  become: yes
  shell: "docker push {{ hostvars[item[1]]['ansible_eth0']['ipv4']['address'] }}:5000/registry/{{ item[0].name }}"
  with_nested:
    - "{{ images }}"
    - "{{ groups['VMManager'] }}"

