---

- name: init docker swarm
  command: docker swarm init --advertise-addr "{{ inventory_hostname }}"
  when: inventory_hostname in groups['VMManager']

- name: retrieve manager token
  command: docker swarm join-token --quiet manager
  register: token
  when: inventory_hostname in groups['VMManager']

- name: add workers to manager
  command: docker swarm join --token "{{ token.stdout }}" "{{ inventory_hostname }}":2377
  when: inventory_hostname in groups['VMWorker']
