---
- tasks:
    - name: init docker swarm
        command: docker swarm init --advertise-addr 172.16.226.34
        when: inventory_hostname in groups['vmmanager']

    - name: retrieve token
        command: docker swarm join-token --quiet worker
        register: token
        when: inventory_hostname in groups['vmmanager']

    - name: join manager
        command: docker_swarm join --token "{{ token.stdout }}" 172.16.226.88
        when: inventory_hostname in groups['vmworker']