---
- name: stop registry
  become: yes
  ignore_errors: yes
  shell: "docker service rm registry > /dev/null 2>&1"
  when:
    - inventory_hostname in groups['VMManager']

- name: create registry
  become: yes
  ignore_errors: yes
  shell: "docker service create --publish 5000:5000 --name registry registry:latest"
  when:
    - inventory_hostname in groups['VMManager']
