---

- name: stop registry
  become: yes
  shell: 'docker stop Docker'
  ignore_errors: yes
  when:
    - inventory_hostname in groups['VMManager']

- name: check if registry exists
  become: yes
  shell: 'docker ps -a | grep Docker'
  register: registry_exists
  failed_when: "registry_exists.rc == 2"
  when:
    - inventory_hostname in groups['VMManager']
  
- name: install dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - libffi-dev
    - libssl-dev

- name: add jessie-backports repository
  become: yes
  apt_repository:
    repo: deb http://ftp.debian.org/debian/ jessie-backports main
    state: present
    update_cache: yes

- name: install pyopenssl
  become: yes
  apt:
    name: "{{ item }}"
    default_release: jessie-backports
    state: latest
  with_items:
    - python3-openssl
    - python-openssl

- name: install rsync
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - rsync
    
- name: install pyopenssl
  become: yes
  pip:
    name: pip
    state: latest

- name: create ssl crt directory
  become: yes
  file:
    path: /etc/docker/certs.d/crt/etna.docker.registry
    state: directory

- name: create ssl csr directory
  become: yes
  file:
    path: /etc/docker/certs.d/csr/etna.docker.registry
    state: directory

- name: create private ssl directory
  become: yes
  file:
    path: /etc/docker/certs.d/private/etna.docker.registry
    state: directory
  when:
    - inventory_hostname in groups['VMManager']

- name: generate ssl private key
  become: yes
  openssl_privatekey:
    path: /etc/docker/certs.d/private/etna.docker.registry/ca.pem
  when:
    - inventory_hostname in groups['VMManager']

- name: generate ssl csr
  become: yes
  openssl_csr:
    common_name: etna.docker.registry
    path: /etc/docker/certs.d/csr/etna.docker.registry/ca.csr
    privatekey_path: /etc/docker/certs.d/private/etna.docker.registry/ca.pem
  when:
    - inventory_hostname in groups['VMManager']
    
- name: generate ssl certificate
  become: yes
  openssl_certificate:
    path: /etc/docker/certs.d/crt/etna.docker.registry/ca.crt
    privatekey_path: /etc/docker/certs.d/private/etna.docker.registry/ca.pem
    csr_path: /etc/docker/certs.d/csr/etna.docker.registry/ca.csr
    provider: selfsigned
  when:
    - inventory_hostname in groups['VMManager']

- name: copy certificates to workers
  become: yes
  fetch:
    src: /etc/docker/certs.d/crt/etna.docker.registry/ca.crt
    dest: /etc/docker/certs.d/crt/etna.docker.registry/ca.crt
    # when:
      # - inventory_hostname in groups['VMManager']

- name: create registry
  become: yes
  shell: "docker service  -p 5000:5000 --restart=always --name Docker --insecure-registry=\"{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}:5000\" registry:2"
  when:
    - inventory_hostname in groups['VMManager']
    - registry_exists == ""

- name: run registry
  become: yes
  shell: 'docker start Docker' 
  when:
    - inventory_hostname in groups['VMManager']
