---
- name: create registry
  command: docker create -t --name registry
  when:
    - inventory_hostname in groups['VMManager']
    - [ ! "$(docker ps -a | grep registry)" ]

- name: create volume
  command: docker run -d -p 5000:5000 --name Docker
  when:
    - inventory_hostname in groups['VMManager']
    -
