---
- name: stop registry
  become: yes
  shell: 'docker stop Docker'
  ignore_errors: yes
  when:
    - inventory_hostname in groups['VMManager']

- name: check if registry exists
  become: yes
  shell: 'docker ps -a | grep Docker'
  register: registry_exists
  failed_when: "registry_exists.rc == 2"

- name: create registry
  become: yes
  shell: "docker run -d -p 5000:5000 --restart=always --name Docker --insecure-registry=\"{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}:5000\" registry:2"
  when:
    - inventory_hostname in groups['VMManager']
    - registry_exists == ""

- name: run registry
  become: yes
  shell: 'docker start Docker' 
  when:
    - inventory_hostname in groups['VMManager']
