---
- name: install dependencies
  when: inventory_hostname in groups['VMManager']
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - curl
    - openssh-server
    - ca-certificates

- name: install gitlab
  apt:
    name: gitlab
    update_cache: yes
    state: latest
  when: 
    - inventory_hostname in groups['VMManager']
